# 프로젝트 유형별 평가 체인 가중치 설정
# 이 파일은 프로젝트 유형에 따라 각 평가 체인에 적용될 가중치를 정의합니다.
# 모든 가중치의 합은 1.0이 되어야 하며, 그렇지 않을 경우 자동으로 정규화됩니다.

# 평가 체인별 설명:
# - business_value: 비즈니스 가치 및 수익성
# - technical_feasibility: 기술적 실현 가능성
# - cost_analysis: 비용 효율성 분석
# - user_engagement: 사용자 참여도 및 만족도
# - innovation: 혁신성 및 창의성
# - social_impact: 사회적 영향도
# - sustainability: 지속가능성
# - accessibility: 접근성
# - network_effect: 네트워크 효과

weights:
  # PainKiller 유형: 명확한 문제를 해결하는 필수적인 솔루션
  # 비즈니스 가치, 기술적 실현가능성, 비용 효율성에 높은 가중치 부여
  painkiller:
    business_value: 0.25
    technical_feasibility: 0.20
    cost_analysis: 0.20
    user_engagement: 0.10
    innovation: 0.10
    social_impact: 0.05
    sustainability: 0.05
    accessibility: 0.03
    network_effect: 0.02
    
  # Vitamin 유형: 사용자 경험을 개선하는 부가가치 솔루션
  # 사용자 참여도, 혁신성, 사회적 영향에 높은 가중치 부여
  vitamin:
    user_engagement: 0.25
    innovation: 0.20
    social_impact: 0.20
    business_value: 0.10
    sustainability: 0.10
    accessibility: 0.05
    technical_feasibility: 0.05
    cost_analysis: 0.03
    network_effect: 0.02
    
  # Balanced 유형: 문제 해결과 경험 개선을 모두 포함하는 복합형 솔루션
  # 모든 평가 항목에 균등한 가중치 부여
  balanced:
    business_value: 0.12
    technical_feasibility: 0.12
    cost_analysis: 0.11
    user_engagement: 0.12
    innovation: 0.12
    social_impact: 0.11
    sustainability: 0.10
    accessibility: 0.10
    network_effect: 0.10

# 기본 설정 및 시스템 동작 옵션
default_settings:
  # 가중치 합계 허용 오차 (정규화 임계값)
  # 가중치 합이 1.0 ± 이 값 범위를 벗어나면 자동 정규화 수행
  weight_sum_tolerance: 0.01
  
  # 오류 처리 설정
  # 분류 실패시 기본값 사용하지 않고 예외 발생
  raise_on_classification_failure: true
  
  # 로깅 설정
  log_weight_changes: true      # 가중치 변경 시 로그 기록
  log_normalization: true       # 가중치 정규화 시 로그 기록
  log_classification: true      # 프로젝트 분류 결과 로그 기록
  
  # 성능 설정
  enable_caching: true          # 분류 결과 캐싱 활성화
  cache_ttl_seconds: 3600       # 캐시 유효 시간 (초)

# 가중치 검증 규칙
validation:
  # 각 가중치의 최소값 (0.0 - 1.0)
  min_weight: 0.0
  # 각 가중치의 최대값 (0.0 - 1.0)
  max_weight: 1.0
  # 필수 평가 체인 목록 (이 체인들은 반드시 가중치가 설정되어야 함)
  required_chains:
    - business_value
    - technical_feasibility
    - cost_analysis
    - user_engagement
    - innovation
    - social_impact
    - sustainability
    - accessibility
    - network_effect