BusinessValue:
  pain_killer:
    - 타겟 고객이 이 비용 문제로 인해 사업 존속이 위험한 상황인가?
    - 현재 해결책이 전혀 없거나 접근 불가능한 상태인가?
    - 문제 해결 지연 시 손실이 기하급수적으로 증가하는가?
    - 고객이 높은 비용을 지불하더라도 즉시 해결하려 하는가?
  vitamin:
    - 비용 최적화를 통해 고객의 운영 효율성이 눈에 띄게 개선되는가?
    - 경쟁사 대비 명확한 가격 경쟁력과 차별화된 가치를 제공하는가?
    - 고객이 투자 대비 만족할 만한 부가가치를 얻을 수 있는가?
    - 프리미엄 가격에도 불구하고 선택받을 차별화 요소가 있는가?

SocialImpact:
  pain_killer:
    - 대상 사회적 약자들이 생존 위기나 안전 위험에 직면해 있는가?
    - 기존 지원 체계로는 절대 해결될 수 없는 사각지대 문제인가?
    - 방치 시 개인과 사회 전체에 심각한 피해가 확산되는가?
    - 당사자들이 절망적이고 긴급한 도움을 간절히 필요로 하는가?
  vitamin:
    - 사회적 약자들의 삶의 질을 의미 있게 향상시킬 수 있는가?
    - 기존 지원을 보완하여 더 포괄적이고 효과적인 도움을 제공하는가?
    - 장기적으로 사회 전체의 인식 개선과 문화 변화를 이끌 수 있는가?
    - 지속 가능한 사회적 가치 창출과 선순환 구조를 만들 수 있는가?

BusinessValueProposal:
  pain_killer:
    - 기업이 규제 위반이나 컴플라이언스 리스크로 막대한 손실을 입고 있는가?
    - 해당 문제로 인해 기업의 핵심 사업이 중단되거나 경쟁력을 상실하는가?
    - 임계점에 도달하여 즉각적인 해결 없이는 생존이 어려운가?
    - 의사결정권자가 예산 제약에도 불구하고 반드시 해결해야 한다고 인식하는가?
  vitamin:
    - 기업의 운영 효율성을 측정 가능한 수준으로 개선시키는가?
    - 고객 경험이나 직원 만족도 향상을 통해 무형 가치를 창출하는가?
    - 중장기적으로 브랜드 가치와 시장 포지셔닝을 강화하는가?
    - 혁신적인 업무 방식이나 프로세스 개선을 통해 차별화를 제공하는가?

UserEngagement:
  pain_killer:
    - 사용자가 심각한 정신적 고통이나 사회적 고립 상태에 있는가?
    - 기존 해결책들이 접근성, 비용, 효과성 면에서 근본적 한계가 있는가?
    - 문제가 악화되면서 일상생활이나 사회적 기능에 심각한 장애가 발생하는가?
    - 전문적 치료나 교육적 개입이 생존과 회복에 필수적인가?
  vitamin:
    - 사용자에게 몰입도 높은 재미와 의미 있는 여가 경험을 제공하는가?
    - 기존 엔터테인먼트 옵션과 차별화된 독특하고 매력적인 경험인가?
    - 지속적인 참여를 유도하는 중독성 있는 재미 요소가 설계되어 있는가?
    - 커뮤니티 형성과 사회적 연결을 통해 소속감과 성취감을 제공하는가?

NetworkEffect:
  pain_killer:
    - 현재 매칭이나 거래 실패로 인해 참여자들이 실질적 손실을 겪고 있는가?
    - 기존 중개 방식의 비효율성으로 시장 자체가 제대로 작동하지 않는가?
    - 플랫폼 없이는 양쪽 참여자들이 서로를 찾을 방법이 전혀 없는가?
    - 거래 성사율이 낮아 참여자들이 기회 비용과 시간 손실을 겪고 있는가?
  vitamin:
    - 기존 거래 방식보다 현저히 편리하고 효율적인 사용자 경험을 제공하는가?
    - 참여자들에게 추가적인 가치나 인사이트를 제공하는 부가 서비스가 있는가?
    - 네트워크 참여만으로도 얻을 수 있는 차별화된 혜택이나 경험이 있는가?
    - 참여자들의 만족도와 충성도를 높이는 독특한 플랫폼 경험을 제공하는가?

TechnicalFeasibility:
  pain_killer:
    - 현재 기술 부재로 인해 핵심 문제 해결이 완전히 불가능한 상황인가?
    - 기존 기술들의 근본적 한계로 인해 사업이나 서비스가 실패하고 있는가?
    - 기술적 혁신 없이는 생존이나 경쟁력 확보가 절대 불가능한가?
    - 기술 완성도가 직접적으로 성공과 실패를 가르는 결정 요인인가?
  vitamin:
    - 최신 기술을 활용하여 사용자에게 혁신적이고 차별화된 경험을 제공하는가?
    - 기존 기술적 해결책보다 성능, 편의성, 확장성 면에서 우월한가?
    - 기술적 우위를 통해 경쟁사들이 쉽게 모방할 수 없는 진입장벽을 구축하는가?
    - 사용자 편의성과 만족도를 기술적으로 획기적으로 개선하는가?

Innovation:
  pain_killer:
    - 기존에 전혀 인식되지 않았던 새로운 문제를 발견하고 정의했는가?
    - 기존 솔루션들로는 절대 해결될 수 없는 근본적 한계를 극복하는가?
    - 혁신적 접근법 없이는 문제 해결이 원천적으로 불가능한가?
    - 새로운 패러다임을 제시하여 시장과 산업 전체를 변화시킬 잠재력이 있는가?
  vitamin:
    - 기존 방식을 창의적으로 개선하여 사용자 경험을 획기적으로 향상시키는가?
    - 독창적이고 참신한 아이디어로 시장에서 화제성과 관심을 끌 수 있는가?
    - 장기적으로 지속 가능한 차별화와 브랜드 우위를 확보할 수 있는가?
    - 예술적, 기술적, 비즈니스적 창의성이 조화롭게 결합된 혁신인가?

Accessibility:
  pain_killer:
    - 접근성 부족으로 인해 필수 서비스를 이용하지 못해 생존이 위험한가?
    - 디지털 격차나 물리적 장벽으로 인해 기본권이 침해받고 있는가?
    - 접근성 문제가 사회적 불평등과 격차를 심화시키고 있는가?
    - 접근 불가능한 상황이 당사자들에게 절망감과 좌절감을 주고 있는가?
  vitamin:
    - 다양한 사용자층의 편의성과 포용성을 의미 있게 개선하는가?
    - 기존 서비스보다 더 많은 사람들이 쉽고 편리하게 이용할 수 있는가?
    - 사용자 경험의 장벽을 낮춰 참여도와 만족도를 높이는가?
    - 소외계층을 포함한 모든 사용자에게 공평하고 양질의 경험을 제공하는가?

Sustainability:
  pain_killer:
    - 환경 파괴나 사회적 문제로 인해 생존 기반 자체가 위협받고 있는가?
    - 기존 방식의 지속으로 인해 돌이킬 수 없는 임계점에 도달했는가?
    - 지속가능성 확보 실패 시 미래 세대의 생존이 위험해지는가?
    - 환경 규제나 사회적 책임을 다하지 못해 존속 자체가 어려운가?
  vitamin:
    - 장기적 환경 보전과 사회적 가치 창출에 의미 있게 기여하는가?
    - 지속가능한 소비와 생활 문화 확산에 긍정적 영향을 미치는가?
    - 환경친화적 브랜딩을 통해 소비자 선호도와 충성도를 높이는가?
    - 지속가능성을 통한 차별화로 새로운 시장 기회를 창출하는가?