# AI 모델 설정
# 이 파일은 프로젝트 분류 및 평가에 사용되는 AI 모델의 설정을 정의합니다.

# 기본 모델 설정
model:
  # 사용할 기본 모델
  default_model: "nova_lite"
  
  # 모델별 설정
  models:
    nova_lite:
      # 모델 이름
      name: "Nova Lite"
      # 최대 토큰 수
      max_tokens: 4000
      # 온도 설정 (창의성 조절, 0.0-1.0)
      temperature: 0.3
      # 응답 다양성 조절 (0.0-1.0)
      top_p: 0.9
      # 타임아웃 (초)
      timeout_seconds: 30
      
    nova_pro:
      name: "Nova Pro"
      max_tokens: 8000
      temperature: 0.2
      top_p: 0.8
      timeout_seconds: 60

# 프로젝트 분류 모델 설정
classification_model:
  # 분류에 사용할 모델
  model_name: "nova_lite"
  
  # 분류 프롬프트 설정
  prompt_settings:
    # 시스템 프롬프트 사용 여부
    use_system_prompt: true
    # 예시 포함 여부
    include_examples: true
    # 컨텍스트 길이 제한
    max_context_length: 3000
    
  # 분류 결과 후처리 설정
  post_processing:
    # 신뢰도 보정 활성화
    confidence_calibration: true
    # 결과 검증 활성화
    result_validation: true

# 평가 체인 모델 설정
evaluation_model:
  # 평가에 사용할 모델
  model_name: "nova_lite"
  
  # 평가 프롬프트 설정
  prompt_settings:
    # 평가 기준 포함 여부
    include_criteria: true
    # 점수 범위 명시 여부
    specify_score_range: true
    # 근거 요구 여부
    require_reasoning: true
    
  # 평가 결과 후처리 설정
  post_processing:
    # 점수 정규화 활성화
    score_normalization: true
    # 이상치 탐지 활성화
    outlier_detection: true

# API 설정
api:
  # API 키 환경 변수명
  api_key_env: "NOVA_API_KEY"
  
  # API 엔드포인트
  endpoint: "https://api.nova.ai/v1"
  
  # 요청 제한 설정
  rate_limiting:
    # 분당 최대 요청 수
    requests_per_minute: 60
    # 시간당 최대 토큰 수
    tokens_per_hour: 100000
    
  # 재시도 설정
  retry_settings:
    # 최대 재시도 횟수
    max_retries: 3
    # 재시도 간격 (초)
    retry_delay: 2
    # 백오프 배수
    backoff_multiplier: 2

# 캐싱 설정
caching:
  # 모델 응답 캐싱 활성화
  enable_response_caching: true
  
  # 캐시 유효 시간 (초)
  cache_ttl: 3600
  
  # 캐시 크기 제한 (MB)
  max_cache_size_mb: 100
  
  # 캐시 키 생성 방식
  cache_key_strategy: "content_hash"

# 로깅 설정
logging:
  # 모델 호출 로깅
  log_model_calls: true
  
  # 응답 시간 로깅
  log_response_times: true
  
  # 토큰 사용량 로깅
  log_token_usage: true
  
  # 오류 상세 로깅
  log_detailed_errors: true