# 시스템 전반 설정
# 이 파일은 프로젝트 유형 평가 시스템의 전반적인 동작을 제어하는 설정을 포함합니다.

# 시스템 정보
system:
  name: "Project Type Evaluation System"
  version: "1.0.0"
  description: "프로젝트 자료를 분석하여 유형을 분류하고 가중치를 적용한 평가를 제공하는 시스템"

# 실행 환경 설정
runtime:
  # 디버그 모드 활성화
  debug_mode: false
  
  # 상세 로깅 활성화
  verbose_logging: false
  
  # 성능 측정 활성화
  performance_monitoring: true
  
  # 병렬 처리 설정
  parallel_processing: true
  max_workers: 4

# 데이터 처리 설정
data_processing:
  # 입력 데이터 검증 활성화
  validate_input: true
  
  # 결과 데이터 검증 활성화
  validate_output: true
  
  # 데이터 전처리 활성화
  enable_preprocessing: true
  
  # 최대 처리 가능한 파일 크기 (MB)
  max_file_size_mb: 100
  
  # 지원하는 파일 형식
  supported_formats:
    - "pdf"
    - "docx"
    - "pptx"
    - "mp4"
    - "avi"
    - "mov"

# 오류 처리 설정
error_handling:
  # 오류 발생 시 계속 진행 여부
  continue_on_error: true
  
  # 최대 재시도 횟수
  max_retries: 3
  
  # 재시도 간격 (초)
  retry_delay_seconds: 1
  
  # 오류 로그 상세 레벨
  error_log_level: "WARNING"

# 출력 설정
output:
  # 결과 포맷
  format: "json"
  
  # 소수점 자릿수
  decimal_places: 2
  
  # 한국어 출력 활성화
  korean_output: true
  
  # 상세 결과 포함 여부
  include_detailed_results: true
  
  # 실행 시간 포함 여부
  include_execution_time: true

# 보안 설정
security:
  # 입력 데이터 검증 활성화
  validate_input_data: true
  
  # 악성 파일 검사 활성화
  malware_scan: false
  
  # 로그에서 민감한 정보 마스킹
  mask_sensitive_data: true

# 알림 설정
notifications:
  # 경고 알림 활성화
  enable_warnings: true
  
  # 오류 알림 활성화
  enable_errors: true
  
  # 성공 알림 활성화
  enable_success: false
  
  # 알림 레벨 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  notification_level: "WARNING"